### ISSUE TITLE
Latest release 5992 breaks UI tests of downstream plugins

### ISSUE THREAD

**Issue by uhafner** [jenkinsci/acceptance-test-harness#1718]
[Latest release](https://github.com/jenkinsci/acceptance-test-harness/releases/tag/5992.v39030e88deb_3) somehow breaks the downstream UI tests of my plugins:

- https://github.com/jenkinsci/warnings-ng-plugin/pull/1829
- https://github.com/jenkinsci/git-forensics-plugin/pull/825

I tried to backtrack the versions and it seems to be related to https://github.com/jenkinsci/acceptance-test-harness/pull/1709

**Comment by basil** [comment]
The issues in `warnings-ng-plugin` and `git-forensics-plugin` caused by #1709 have been fixed in #1719. If there are additional issues in `warnings-ng-plugin` caused by other PRs, a separate ticket should be filed and the author(s) of those other PRs notified. I am locking this conversation so that I am not notified about issues not caused by me.
