### ISSUE TITLE
Don't build ATH image on every split

### ISSUE THREAD

**Issue by timja** [jenkinsci/acceptance-test-harness#988]
It takes ~3.5 minutes to build and has flaked at least once.

It would be good to build it once and run a smoke test on it and then use a published image for the rest, or something like that.
Or even build and publish and then use the published version.

**Comment by dduportal** [comment]
Make sense: since https://github.com/jenkinsci/acceptance-test-harness/pull/905 the image is prebuilt and pushed to an external registry.

Since this build uses expensive highmem instances, these minutes are good to avoid spending.

For information, nthe infra team always provides the same `jenkins` user with an UID of `1001`as per https://github.com/jenkins-infra/packer-images/blob/977ec35a3cba91abc7c0d3fe704467d450254005/provisioning/ubuntu-provision.sh#L31-L35 so that should be a nice improvement.

**Comment by dduportal** [comment]
https://github.com/jenkinsci/acceptance-test-harness/pull/1168
